name: chatbotapp
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.10.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  http: ^1.3.0
  flutter_spinkit: ^5.2.1
  animated_text_kit: ^4.2.3
  provider: ^6.1.2
  shared_preferences: ^2.2.3

  # Auth (Google + email/password) via Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/icon/robot.png
    - assets/icon/typing.png

  fonts:
    - family: fontMain
      fonts:
        - asset: assets/fonta/Poppins-Regular.ttf

flutter_icons:
  android: true
  ios: true
  web:
    generate: true
  image_path: assets/icon/robot.png
  min_sdk_android: 21
